name: "Build and Deploy Pages Site"

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: 
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: use node.js 
        uses: actions/setup-node@v2.5.1
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: build
        run: |
          npm install -g
          npm run build
          npm run env -- next export -o build

      - name: run tests
        run: npm test
        env:
          CI: true
          FORCE_COLOR: 1

      - name: Archive build output
        run: "tar --dereference --directory build/ -cvf artifact.tar ."

      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: github-pages
          path: artifact.tar
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1.0.1
